In [16]:
import pandas as pd
from pathlib import Path

file_path = Path("../data/2025 County Health Rankings Data - v4.xlsx")

In [17]:
xls = pd.ExcelFile(file_path)
xls.sheet_names

['Introduction',
 'Select Measure Data',
 'Select Measure Sources & Years',
 'Additional Measure Data',
 'Addtl Measure Sources & Years',
 'Health Groups']

In [21]:
select_df.shape

(3211, 225)

In [24]:
select_df = pd.read_excel(
    file_path,
    sheet_name="Select Measure Data",
    header=1
)

select_df.head()

,FIPS,State,County,Unreliable,Deaths,Years of Potential Life Lost Rate,95% CI - Low,95% CI - High,National Z-Score,YPLL Rate (Hispanic (all races)),...,Injury Death Rate (Non-Hispanic 2+ races) 95% CI - Low,Injury Death Rate (Non-Hispanic 2+ races) 95% CI - High,Injury Death Rate (Non-Hispanic White),Injury Death Rate (Non-Hispanic White) 95% CI - Low,Injury Death Rate (Non-Hispanic White) 95% CI - High,# Associations,Social Association Rate,National Z-Score.27,% Household Income Required for Child Care Expenses,National Z-Score.28
0,1000,Alabama,NaN,NaN,102760.0,11853.247248,11744.014820,11962.479676,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,5916.0,11.658760,NaN,25.547114,NaN
1,1001,Alabama,Autauga,NaN,1008.0,9938.263382,9021.297133,10855.229632,-0.144182,NaN,...,NaN,NaN,66.353516,55.322574,77.384459,67.0,11.211700,0.043429,21.835108,-0.961825
2,1003,Alabama,Baldwin,NaN,3944.0,8957.112686,8499.339223,9414.886148,-0.400274,4636.48424,...,NaN,NaN,86.954622,81.060141,92.849104,239.0,9.698298,0.308739,19.354057,-1.316051
3,1005,Alabama,Barbour,NaN,587.0,12738.656137,11133.499025,14343.813250,0.586752,NaN,...,NaN,NaN,92.500356,69.083690,121.301910,22.0,8.904720,0.447859,28.579628,0.001105
4,1007,Alabama,Bibb,NaN,509.0,11708.948038,10166.716823,13251.179253,0.317987,NaN,...,NaN,NaN,110.157489,88.691939,135.248986,19.0,8.634401,0.495248,26.582776,-0.283990

In [38]:
cols = [
    "FIPS",
    "State",
    "County",
    "Primary Care Physicians Rate",
    "Mental Health Provider Rate",
    "% Uninsured",
    "% Fair or Poor Health",
    "Average Number of Physically Unhealthy Days",
    "Preventable Hospitalization Rate",
    "% Children in Poverty",
    "% Severe Housing Problems",
]

nc_df = select_df.loc[select_df["State"] == "North Carolina", cols].copy()
nc_df = nc_df.iloc[1:].copy()
nc_df.head()

,FIPS,State,County,Primary Care Physicians Rate,Mental Health Provider Rate,% Uninsured,% Fair or Poor Health,Average Number of Physically Unhealthy Days,Preventable Hospitalization Rate,% Children in Poverty,% Severe Housing Problems
1939,37001,North Carolina,Alamance,38.53299,192.00179,12.580197,19.7,4.124829,2740.0,16.0,13.157895
1940,37003,North Carolina,Alexander,19.10272,90.47789,11.926507,17.3,4.185033,2975.0,17.4,9.633197
1941,37005,North Carolina,Alleghany,99.55652,229.23647,17.302539,21.1,4.637557,2237.0,24.5,12.893082
1942,37007,North Carolina,Anson,45.33092,86.76988,12.467217,23.4,4.657966,3011.0,33.0,18.794749
1943,37009,North Carolina,Ashe,48.66909,177.36393,13.603904,17.8,4.203436,2232.0,22.0,8.997868

In [37]:
nc_df.isna().sum().sort_values(ascending=False)

Primary Care Physicians Rate                   2
Mental Health Provider Rate                    1
FIPS                                           0
County                                         0
State                                          0
% Uninsured                                    0
% Fair or Poor Health                          0
Average Number of Physically Unhealthy Days    0
Preventable Hospitalization Rate               0
% Children in Poverty                          0
% Severe Housing Problems                      0
dtype: int64

In [39]:
nc_df[nc_df["Primary Care Physicians Rate"].isna()]

,FIPS,State,County,Primary Care Physicians Rate,Mental Health Provider Rate,% Uninsured,% Fair or Poor Health,Average Number of Physically Unhealthy Days,Preventable Hospitalization Rate,% Children in Poverty,% Severe Housing Problems
1975,37073,North Carolina,Gates,NaN,NaN,9.177892,18.9,4.300862,3109.0,19.5,13.164251
2027,37177,North Carolina,Tyrrell,NaN,28.89338,15.693582,20.1,4.458810,2930.0,29.9,13.074205

Note: Gates and Tyrrell counties are missing provider rate data

In [40]:
nc_df.shape

(100, 11)

In [41]:
nc_df.describe()

,FIPS,Primary Care Physicians Rate,Mental Health Provider Rate,% Uninsured,% Fair or Poor Health,Average Number of Physically Unhealthy Days,Preventable Hospitalization Rate,% Children in Poverty,% Severe Housing Problems
count,100.000000,98.000000,99.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,37100.000000,52.276190,226.989537,12.464222,19.141000,4.218005,2787.040000,21.769000,13.992427
std,58.022984,29.292413,162.937952,2.161015,3.442752,0.412280,724.785192,7.542107,2.840078
min,37001.000000,5.329920,21.706100,8.124213,12.100000,3.204973,1330.000000,8.200000,8.928571
25%,37050.500000,32.661185,112.314800,11.011617,16.975000,3.932816,2236.500000,15.950000,11.865192
50%,37100.000000,46.343655,192.001790,12.267668,18.900000,4.221093,2829.500000,20.950000,13.474931
75%,37149.500000,64.544652,278.677970,13.465909,21.125000,4.491932,3192.500000,25.550000,15.723301
max,37199.000000,182.020900,895.611110,19.418414,27.200000,5.179660,5148.000000,42.900000,21.210014